disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Arlington Care Home"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo_icon.png"
description = "Arlington Care Home at 2545 Arlington Blvd., El Cerrito, California 94530"
secondaryLogo = "logo_icon.png"

["params.author"]
name = ""
