[[main]]
none = "none"

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "xpTGuO6URB"
weight = 4

[[main]]
name = "Amenities"
pageRef = "amenities"
identifier = "vYU8I7snmb"
weight = 3

[[main]]
name = "About"
pageRef = "about"
identifier = "qOSEpZ3HFg"
weight = 1

[[main]]
name = "Services"
pageRef = "services"
identifier = "HFKdGSGVeL"
weight = 2

[[footer]]
none = "none"
