[[main]]
none = "none"

[[main]]
name = "Contact"
pageRef = "contact"
identifier = "xpTGuO6URB"
weight = 9_999

[[main]]
name = "Amenities"
pageRef = "amenities"
identifier = "vYU8I7snmb"
weight = 9_999

[[main]]
name = "About"
pageRef = "about"
identifier = "qOSEpZ3HFg"
weight = 9_999

[[footer]]
none = "none"
